### ISSUE TITLE
[FR] Upload Duplicated Games

### ISSUE THREAD

**Issue by gromber** [israpps/HDL-Batch-installer#33]
### Explanation

Hi, i want a option to upload a modded version of the same game i already have unotuched in the hard drive, for example, now i want to test a spanish fan dubbed version of pal code veronica x  http://www.lugerdorada.com.es, but i want to keep the original game, without remove it and share the same save in both cases, because i want only to test that patched iso as an alternative of the original game.

Thanks.

### fature related

- [x] game Installation
- [x] Title Database
- [ ] ART Downloader
- [ ] Game management
- [x] HDD management
- [ ] Others...

### other checks

- [x] I've checked if such feature exists on [Latest version](https://github.com/israpps/HDL-Batch-installer/releases/)
- [ ] This Feature requires an update of WxWidgets
- [ ] Needs an update of [HDL Dump](https://github.com/ps2homebrew/hdl-dump)

**Comment by israpps** [comment]
Hi, to install this game without getting the error of `game already exists` make sure to use a custom name (disable database loading) and make sure that the title differs from the installed one on the first 16 chars

**Comment by gromber** [comment]
Done, thanks for the help and all your work in this app!

**Comment by israpps** [comment]
Just for the record

This has to be done this way because HDL Dump uses the game title to fill the remaining space on the partition name (rectifing all letters to uppercase and filtering illegal chars as `_`, the ammount of chars of the title that get passed into the partition title is ~`16`, so that's why the first `16` char's can't be equal to any already installed game.

Another option would be to alter the partition name of the already installed game, wich should not bring negative effects unless you are using a PSX-DESR xmb menu and OPL Launcher
