### ISSUE TITLE
HDL-Batch-installer supports Japanese and Ryukyuan languages

### ISSUE THREAD

**Issue by kuragehimekurara1** [israpps/HDL-Batch-installer#51]
I want to support HDL-Batch-installer in Japanese and Ryukyuan languages. How should I translate it?

**Comment by israpps** [comment]
Hi!

Thanks for showing interest on the project!

In order to translate this project, you need to understand how to use the program [POEdit](https://www.google.com/url?sa=t&source=web&rct=j&url=https://poedit.net/&ved=2ahUKEwiyopOY8KP8AhWmppUCHYkOBbIQFnoECCsQAQ&usg=AOvVaw2fHtt0UP7fn_FWKfjn_GE8)

Then, [download the translation template file](https://github.com/israpps/HDL-Batch-installer/releases/download/Latest/Translation-template.7z) and make the translation.

When it is finished, you should send me the `.po` file, (if you know, [make a pull request](https://github.com/israpps/HDL-Batch-installer/pulls) by yourself.

Once the translation is finished, I'll update the program to support the new languages. (The program itself can use the catalogs without updating if the OS is configured on that language, the update is for manually selecting the language)

**Comment by israpps** [comment]
In addition, you may find on the translation text some special character sequences...

For example:
- `\n`: newline
- `%s`: inline replacement for string
- `%d`: inline replacement for integer

And so on.
The editor auto detects those sequences and highlights them in red, so watch out for red text!
